[project]
name = "my_project"
requires-python = ">=3.10,<3.15"
version = "0.1.0"


[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "my_project"
registry_modules = [
    "my_project.components.*",
]


